/*
 * "streamable kanji code filter and converter"
 * Copyright (c) 1998-2002 HappySize, Inc. All rights reserved.
 *
 * LICENSE NOTICES
 *
 * This file is part of "streamable kanji code filter and converter",
 * which is distributed under the terms of GNU Lesser General Public
 * License (version 2) as published by the Free Software Foundation.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with "streamable kanji code filter and converter";
 * if not, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA  02111-1307  USA
 *
 * The authors of this file: PHP3 Internationalization team
 *
 */

#define MBFL_CHP_MMHQENC 1 /* must use Q-encoding in MIME Header encoded-word */

static const unsigned char mbfl_charprop_table[] = {
/* NUL 0  */  MBFL_CHP_MMHQENC,
/* SCH 1  */  MBFL_CHP_MMHQENC,
/* SIX 2  */  MBFL_CHP_MMHQENC,
/* EIX 3  */  MBFL_CHP_MMHQENC,
/* EOT 4  */  MBFL_CHP_MMHQENC,
/* ENQ 5  */  MBFL_CHP_MMHQENC,
/* ACK 6  */  MBFL_CHP_MMHQENC,
/* BEL 7  */  MBFL_CHP_MMHQENC,
/* BS  8  */  MBFL_CHP_MMHQENC,
/* HI  9  */  MBFL_CHP_MMHQENC,
/* LF  10 */  MBFL_CHP_MMHQENC,
/* VI  11 */  MBFL_CHP_MMHQENC,
/* FF  12 */  MBFL_CHP_MMHQENC,
/* CR  13 */  MBFL_CHP_MMHQENC,
/* SO  14 */  MBFL_CHP_MMHQENC,
/* SI  15 */  MBFL_CHP_MMHQENC,
/* SLE 16 */  MBFL_CHP_MMHQENC,
/* CSI 17 */  MBFL_CHP_MMHQENC,
/* DC2 18 */  MBFL_CHP_MMHQENC,
/* DC3 19 */  MBFL_CHP_MMHQENC,
/* DC4 20 */  MBFL_CHP_MMHQENC,
/* NAK 21 */  MBFL_CHP_MMHQENC,
/* SYN 22 */  MBFL_CHP_MMHQENC,
/* EIB 23 */  MBFL_CHP_MMHQENC,
/* CAN 24 */  MBFL_CHP_MMHQENC,
/* EM  25 */  MBFL_CHP_MMHQENC,
/* SLB 26 */  MBFL_CHP_MMHQENC,
/* ESC 27 */  MBFL_CHP_MMHQENC,
/* FS  28 */  MBFL_CHP_MMHQENC,
/* GS  29 */  MBFL_CHP_MMHQENC,
/* RS  30 */  MBFL_CHP_MMHQENC,
/* US  31 */  MBFL_CHP_MMHQENC,
/* SP  32 */  MBFL_CHP_MMHQENC,
/* !   33 */  0,
/* "   34 */  MBFL_CHP_MMHQENC,
/* #   35 */  MBFL_CHP_MMHQENC,
/* $   36 */  MBFL_CHP_MMHQENC,
/* %   37 */  MBFL_CHP_MMHQENC,
/* &   38 */  MBFL_CHP_MMHQENC,
/* '   39 */  MBFL_CHP_MMHQENC,
/* (   40 */  MBFL_CHP_MMHQENC,
/* )   41 */  MBFL_CHP_MMHQENC,
/* *   42 */  0,
/* +   43 */  0,
/* ,   44 */  MBFL_CHP_MMHQENC,
/* -   45 */  0,
/* .   46 */  MBFL_CHP_MMHQENC,
/* /   47 */  0,
/* 0   48 */  MBFL_CHP_MMHQENC,
/* 1   49 */  MBFL_CHP_MMHQENC,
/* 2   50 */  MBFL_CHP_MMHQENC,
/* 3   51 */  MBFL_CHP_MMHQENC,
/* 4   52 */  MBFL_CHP_MMHQENC,
/* 5   53 */  MBFL_CHP_MMHQENC,
/* 6   54 */  MBFL_CHP_MMHQENC,
/* 7   55 */  MBFL_CHP_MMHQENC,
/* 8   56 */  MBFL_CHP_MMHQENC,
/* 9   57 */  MBFL_CHP_MMHQENC,
/* :   58 */  MBFL_CHP_MMHQENC,
/* ;   59 */  MBFL_CHP_MMHQENC,
/* <   60 */  MBFL_CHP_MMHQENC,
/* =   61 */  0,
/* >   62 */  MBFL_CHP_MMHQENC,
/* ?   63 */  MBFL_CHP_MMHQENC,
/* @   64 */  MBFL_CHP_MMHQENC,
/* A   65 */  0,
/* B   66 */  0,
/* C   67 */  0,
/* D   68 */  0,
/* E   69 */  0,
/* F   70 */  0,
/* G   71 */  0,
/* H   72 */  0,
/* I   73 */  0,
/* J   74 */  0,
/* K   75 */  0,
/* L   76 */  0,
/* M   77 */  0,
/* N   78 */  0,
/* O   79 */  0,
/* P   80 */  0,
/* Q   81 */  0,
/* R   82 */  0,
/* S   83 */  0,
/* T   84 */  0,
/* U   85 */  0,
/* V   86 */  0,
/* W   87 */  0,
/* X   88 */  0,
/* Y   89 */  0,
/* Z   90 */  0,
/* [   91 */  MBFL_CHP_MMHQENC,
/* \   92 */  MBFL_CHP_MMHQENC,
/* ]   93 */  MBFL_CHP_MMHQENC,
/* ^   94 */  MBFL_CHP_MMHQENC,
/* _   95 */  MBFL_CHP_MMHQENC,
/* `   96 */  MBFL_CHP_MMHQENC,
/* a   97 */  0,
/* b   98 */  0,
/* c   99 */  0,
/* d  100 */  0,
/* e  101 */  0,
/* f  102 */  0,
/* g  103 */  0,
/* h  104 */  0,
/* i  105 */  0,
/* j  106 */  0,
/* k  107 */  0,
/* l  108 */  0,
/* m  109 */  0,
/* n  110 */  0,
/* o  111 */  0,
/* p  112 */  0,
/* q  113 */  0,
/* r  114 */  0,
/* s  115 */  0,
/* t  116 */  0,
/* u  117 */  0,
/* v  118 */  0,
/* w  119 */  0,
/* x  120 */  0,
/* y  121 */  0,
/* z  122 */  0,
/* {  123 */  MBFL_CHP_MMHQENC,
/* |  124 */  MBFL_CHP_MMHQENC,
/* }  125 */  MBFL_CHP_MMHQENC,
/* ~  126 */  MBFL_CHP_MMHQENC,
/* DEL 127 */ MBFL_CHP_MMHQENC
};
