trigger:
  batch: true
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

jobs:
  - template: azure/macos/job.yml
    parameters:
      configurationName: MACOS_DEBUG_NTS
      configurationParameters: '--enable-debug --disable-zts'
